#!/usr/bin/env bash
# Redirects localhost and facebook.com

# Localhost-u 127.0.0.2-yə yönləndiririk
sudo sed -i "s/127.0.0.1/127.0.0.2/g" /etc/hosts

# Facebook-u 8.8.8.8-ə yönləndiririk
if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i "s/.*facebook.com/8.8.8.8 facebook.com/" /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
